### ISSUE TITLE
motion_feature315

### ISSUE THREAD

**Issue by SupstarZh** [li-ronghui/LODGE#18]
I found the code in preprocess.py is:
![image](https://github.com/li-ronghui/LODGE/assets/33367196/095a3200-b182-4ac8-9335-e5bb65b49545)

However, the links to Google Drive or Baidu Cloud do not include "motion_feature315" and "music_feature35_edge"
Can you provide these two files? Alternatively, a processing program to obtain these two files can also help me.

**Comment by li-ronghui** [comment]
Hi, we havd already uploaded  the motion and music feature at [Google Driver](https://drive.google.com/file/d/1zQvWG9I0H4U3Zrm8d_QD_ehenZvqfQfS/view) and [百度云](https://pan.baidu.com/s/1gynUC7pMdpsE31wAwq177w?pwd=o9pw). The motion_feature315 and music_feature35_edge are in corresponding motion and music_npy folder.

Otherwise, you can directly download our preprocessed music and dance features from [Google Driver](https://drive.google.com/drive/folders/1cdj8YymfN1BHgggVfGaLjaa9vaEpjPzZ?usp=sharing) or [百度云](https://pan.baidu.com/s/1PQ53ooKxp-EkQvhiv7SKcA?pwd=y0ly) and put them into the ./data/finedance folder if you don't wish to process the data.
